### ISSUE TITLE
Unnecessary memory allocations

### ISSUE THREAD

**Issue by eford** [blhendricks/project-blhendricks#11]
https://github.com/blhendricks/project-blhendricks/blob/d1e5316601c37a1c7b691cf79daeb5cac368d36b/Support_Funcs.jl#L10-L17
Can allocate to correct size once and only update values for one case.
Again, strings are unnecessarily expensive to generate and compare.   A bool, UInt8 or symbol would be more efficient.

**Comment by eford** [comment]
There's also https://docs.julialang.org/en/v1/base/arrays/#Base.BitArray

**Comment by blhendricks** [comment]
Good point, updated the for loop! I will try to update the strings if I can. I do worry about it becoming less readable in the process, but if the performance hit is significant (which I will explore), it's likely worth it.

**Comment by eford** [comment]
Fair point about readability of say a bit array.   But I think symbols are just as easy to read E.g., "cc" becomes :cc.

**Comment by blhendricks** [comment]
Yes, I misunderstood! I actually managed to swap them all to symbols, but
it didn't increase the speed by much (surprisingly). I'm going to see what
I can do to make things a bit cleaner anyway I think with the attributes..
