### ISSUE TITLE
Why collect?

### ISSUE THREAD

**Issue by eford** [blhendricks/project-blhendricks#12]
https://github.com/blhendricks/project-blhendricks/blob/d1e5316601c37a1c7b691cf79daeb5cac368d36b/Support_Funcs.jl#L33
Is there a need to allocate an array for this, rather than leaving as a range?

**Comment by blhendricks** [comment]
Hmm, potentially. I have since removed the section of code this was apart of though as I do not have time to implement it other spectra.
