### ISSUE TITLE
Error type

### ISSUE THREAD

**Issue by eford** [blhendricks/project-blhendricks#13]
https://github.com/blhendricks/project-blhendricks/blob/d1e5316601c37a1c7b691cf79daeb5cac368d36b/Support_Funcs.jl#L80-81
Sure.  Or maybe https://docs.julialang.org/en/v1/base/base/#Core.ErrorException

**Comment by blhendricks** [comment]
Noted! Removed the segment it was in, however, since it was a part of implementation that I can't quite finish in time.
